#:schema node_modules/wrangler/config-schema.json
name = "fancyrocks"
main = "src/server.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[r2_buckets]]
binding = "FancyRocksImages"
bucket_name = "fancyrocks-images"
